# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='foto',
            field=models.ImageField(upload_to='static/upload/images/'),
        ),
    ]
